/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: muruku (https://sketchfab.com/muruku)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bulbasaur-ac6a2312cfe2441ca63c1a2785542360
Title: bulbasaur
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../src/assets/3d/bulbasaur.glb"
  );
  const { actions } = useAnimations(animations, group);

  // Use useFrame to update rotation on each frame
  useFrame(() => {
    if (group.current) {
      group.current.rotation.y += 0.01; // Adjust the rotation speed as needed
    }
  });

  return (
    <group ref={group} {...props} position={[0, -2, -0.5]} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="a44840bb1ba84152bec0b502ca828c35fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="bulbasaur"
                  position={[451.86954, 56.98589, 78.51361]}
                  rotation={[-1.07292, 0, 0]}
                  scale={22.14226}
                >
                  <mesh
                    name="bulbasaur_bulbasaur_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bulbasaur_bulbasaur_0.geometry}
                    material={materials.bulbasaur}
                  />
                  <mesh
                    name="bulbasaur_outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bulbasaur_outline_0.geometry}
                    material={materials.outline}
                  />
                </group>
                <group
                  name="dome"
                  position={[-9.99014, 130.37169, 120.34074]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[184.32239, 184.32239, 184.57912]}
                >
                  <mesh
                    name="dome_Material006_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.dome_Material006_0.geometry}
                    material={materials["Material.006"]}
                  />
                </group>
                <group
                  name="ground"
                  position={[-10.94641, 130.15657, 123.54493]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={184.32239}
                >
                  <mesh
                    name="ground_ground_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.ground_ground_0.geometry}
                    material={materials.ground}
                  />
                  <mesh
                    name="ground_outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.ground_outline_0.geometry}
                    material={materials.outline}
                  />
                </group>
                <group
                  name="grass"
                  position={[-18.60922, 39.9422, 198.88405]}
                  rotation={[0, 0.15686, 0]}
                  scale={[13.24485, 4.71017, 13.24485]}
                >
                  <mesh
                    name="grass_grass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.grass_grass_0.geometry}
                    material={materials.grass}
                  />
                  <mesh
                    name="grass_grass_2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.grass_grass_2_0.geometry}
                    material={materials.grass_2}
                  />
                </group>
                <group
                  name="plant4"
                  position={[64.71342, 39.38077, 17.6055]}
                  rotation={[-1.82513, 0.11838, 1.65501]}
                  scale={[0.82873, 1.51169, 2.28018]}
                >
                  <mesh
                    name="plant4_plant4_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.plant4_plant4_0.geometry}
                    material={materials.plant4}
                  />
                  <mesh
                    name="plant4_outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.plant4_outline_0.geometry}
                    material={materials.outline}
                  />
                </group>
                <group
                  name="plant2"
                  position={[28.5051, 202.0798, 95.49294]}
                  rotation={[Math.PI, 0.34492, -2.8983]}
                  scale={17.23498}
                >
                  <mesh
                    name="plant2_plant2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.plant2_plant2_0.geometry}
                    material={materials.plant2}
                  />
                  <mesh
                    name="plant2_outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.plant2_outline_0.geometry}
                    material={materials.outline}
                  />
                </group>
                <group
                  name="plant3"
                  position={[84.24441, 175.68854, 216.87112]}
                  rotation={[0, 0.45631, -Math.PI]}
                  scale={[37.6001, 37.60009, 37.6001]}
                >
                  <mesh
                    name="plant3_plant3_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.plant3_plant3_0.geometry}
                    material={materials.plant3}
                  />
                  <mesh
                    name="plant3_outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.plant3_outline_0.geometry}
                    material={materials.outline}
                  />
                </group>
                <group
                  name="plant1"
                  position={[-138.51692, 108.49319, 111.60468]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                  scale={4.28217}
                >
                  <mesh
                    name="plant1_plant1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.plant1_plant1_0.geometry}
                    material={materials.plant1}
                  />
                  <mesh
                    name="plant1_outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.plant1_outline_0.geometry}
                    material={materials.outline}
                  />
                </group>
                <group
                  name="Empty"
                  position={[-2.21591, -24.29228, 120.21624]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group
                    name="Camera"
                    position={[-0.03747, 10.99848, 1.53704]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  >
                    <group name="Object_29" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export default Model;
